Vagrant.configure("2") do |config|

    config.vm.box = "generic/debian11"
  
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "8192"
      vb.cpus = 2
    end

    config.vm.define "app01" do |app|
      app.vm.hostname = "app01.moodle.intern"
      app.vm.network :private_network, ip: "192.168.56.10"
    end

end