---
# - hosts: all
#   name: Deployment
#   remote_user: vagrant
#   gather_facts: false
#   tasks:
#     - debug:
#         var: ansible_facts

- hosts: app01
  remote_user: vagrant
  gather_facts: true
  roles:
    - name: vm_postgres_setup
      tags: vm_postgres_setup
