---
php_version: "8.1"
modules_apache_php:
  - "php{{ php_version }}-iconv"
  - "php{{ php_version }}-mbstring"
  - "php{{ php_version }}-curl"
  - "php{{ php_version }}-tokenizer"
  - "php{{ php_version }}-xmlrpc"
  - "php{{ php_version }}-soap"
  - "php{{ php_version }}-ctype"
  - "php{{ php_version }}-zip"
  - "php{{ php_version }}-gd"
  - "php{{ php_version }}-simplexml"
  - "php{{ php_version }}-dom"
  - "php{{ php_version }}-xml"
  - "php{{ php_version }}-intl"
  - "php{{ php_version }}-pgsql"
  - "libapache2-mod-php{{ php_version }}"

apache_disabled_sites:
  - 000-default.conf

apache_enabled_sites:
  - 