---
- name: Add Postgres Apt Key
  become: true
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add Postgres Apt Repo
  become: true
  ansible.builtin.apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_facts.lsb.codename }}-pgdg main"

- name: Install postgresql
  become: true
  apt:
    name: postgresql
    state: present

- name: Create a new database with name "moodle"
  community.postgresql.postgresql_db:
    name: moodle
    encoding: utf8mb4
    lc_collate: utf8mb4_unicode_ci

- name: Connect to acme database and set user's password with no expire date
  community.postgresql.postgresql_user:
    db: "{{ item.db }}"
    name: "{{ item.name }}"
    password: "{{ item.passord }}"
    priv: "{{ item.priv }}"
  with_items: "{{ postgresql_users }}"