---
- name: Add Postgres Apt Key
  become: true
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add Postgres Apt Repo
  become: true
  ansible.builtin.apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_facts.lsb.codename }}-pgdg main"

- name: Install postgresql
  become: true
  apt:
    name: postgresql
    state: present
